[font]
size = 9


[font.bold]
family = "AurulentSansM Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "AurulentSansM Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "AurulentSansM Nerd Font Mono"
style = "Italic"

[font.normal]
family = "AurulentSansM Nerd Font Mono"
style = "Regular"

[terminal]

[terminal.shell]
args = ["new-session", "-A", "-D", "-s", "main"]
program = "/bin/tmux"
